eventstore:
  image: adbrowne/eventstore
  ports:
    - 1113:1113
    - 2113:2113

get-guid:
  build: get-guid

send-cmd:
  build: send-commands
  links:
    - eventstore:eventstore
    
web:
  image: nginx
  ports:
    - 8080:80
  links:
    - get-guid:get-guid
    - send-cmd:send-cmd
    - eventstore:eventstore
  environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
  volumes:
    - ./web/html:/usr/share/nginx/html
    - ./web/default.conf:/etc/nginx/conf.d/default.conf
