get-guid:
  build: get-guid

web:
  image: nginx
  ports:
    - 8080:80
  links:
    - get-guid:get-guid
  environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
  volumes:
    - ./web/html:/usr/share/nginx/html
    - ./web/default.conf:/etc/nginx/conf.d/default.conf